### PR TITLE
[BottomAppBar] Fix it/bottom app bar cut out

### PR DESCRIPTION
**Pull request by peterfriese**
### Context
FABs can be circular or pill-shaped. As described in #5414, the cutout on BottomAppBar does not take into account pill-shaped FABs.

### The Problem
The UIBezierPath used in the current implementation draws a half circle where the FAB appears. For pill-shaped FABS, this doesn't work, as the cutout needs to made up of two quarter circle and a line connecting them.

### The Fix
I implemented a UIBezierPath that is made up of two quarter circles connected by a line, as well as the remainder of the rectangle that makes up the BottomAppBar's background. By doing so, I was able to provide **one** bezier path for both circular and pill-shaped cutouts, and **one** bezier path for a non-cutout version of the rectangle. This results in a smooth animation between the cutout and non-cutout state.

See https://stackoverflow.com/a/9522806 for an explanation of why the cutout and non-cutout bezier paths need to have the same general structure (e.g. number of path elements, and element types).

Code has been formatted using `git clang-format`.

This PR supersedes #5958, which had been reverted due to incorrect rendering of the cutout (it was not entirely round).

Here is how a pill-shaped FAB will look like:

Pill-shaped FAB on BottomAppBar

Here is a round FAB, rendered using the new code in this PR:

bottomappbar-objc-after

For comparison, here is the same screen, rendered using the previous code. A visual diff shows that the only difference between the two screenshots is the time in the status bar :-)

bottomappbar-objc-before

### CODE REVIEW

**Comment by romoore** [comment]
Ping @wenyuzhang666

**Comment by fluxminds** [comment]
@peterfriese Hi Peter, thanks for sending this PR. I re-ran our CI jobs, there seem to be some errors on "implicit conversion loses floating-point precision: 'double' to 'CGFloat'" Would you mind fixing those? You can click on the Details button on the CI job to view the details. Thank you:)

**Comment by romoore** [comment]
Here are the failures:

```
components/BottomAppBar/src/private/MDCBottomAppBarLayer.m:122:47: error: implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Werror,-Wconversion]
                       startAngle:-180 * M_PI / 180
                                  ~~~~~~~~~~~~^~~~~
components/BottomAppBar/src/private/MDCBottomAppBarLayer.m:123:47: error: implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Werror,-Wconversion]
                         endAngle:-270 * M_PI / 180
                                  ~~~~~~~~~~~~^~~~~
components/BottomAppBar/src/private/MDCBottomAppBarLayer.m:128:47: error: implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Werror,-Wconversion]
                       startAngle:-270 * M_PI / 180
                                  ~~~~~~~~~~~~^~~~~
components/BottomAppBar/src/private/MDCBottomAppBarLayer.m:129:47: error: implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Werror,-Wconversion]
                         endAngle:-360 * M_PI / 180
                                  ~~~~~~~~~~~~^~~~~
```

**Review by fluxminds — CHANGES_REQUESTED** [review]
Left a comment on addressing the CI failure.

**Comment by peterfriese** [comment]
Hi @wenyuzhang666  - thanks for the hints. How can I turn on those checks for local compilation, so I can make sure my fix is correct?

**Comment by fluxminds** [comment]
@peterfriese you can try running `./.kokoro -d bazel -c build -t //components/BottomAppBar` locally to check the fix. Using the kokoro:force-run label on the pull request would be helpful and quick to check it too.

**Comment by romoore** [comment]
Consider using `./.kokoro -d bazel -c build -t //components/BottomAppBar/...` to build all targets in BottomAppBar.

**Comment by peterfriese** [comment]
I tried running the commands you suggested (after installing bazel via homebrew), but this is all I get:

```
Running bazel builds...
🏗️  build with Xcode 10.1...
Rewriting imports for bazel...
INFO: Invocation ID: e2d032dc-65c1-437b-b061-f3b5aceb6256
DEBUG: Rule 'build_bazel_rules_apple' modified arguments {"commit": "62ab92257b9e55fc63dba91a720dadce36da560a", "shallow_since": "1542820899 -0500"} and dropped ["tag"]
DEBUG: Rule 'build_bazel_rules_swift' modified arguments {"commit": "0a7ae28d5708a05b5f3ef79dad00c6ca91054b53", "shallow_since": "1542815492 -0800"} and dropped ["tag"]
DEBUG: Rule 'bazel_skylib' modified arguments {"commit": "3fea8cb680f4a53a129f7ebace1a5a4d1e035914", "shallow_since": "1528913834 -0400"} and dropped ["tag"]
ERROR: /private/var/tmp/_bazel_peterfriese/64605403d0c8c1779c313e5420fa5937/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl:110:35: late-bound attributes must not have a split configuration transition
DEBUG: Rule 'bazel_ios_warnings' modified arguments {"commit": "c3f720c0838af1ee53299aa6efda87cf729146b4", "shallow_since": "1545400728 -0500"} and dropped ["tag"]
ERROR: error loading package 'components/BottomAppBar': in /Users/peterfriese/Workspace/Initiatives/MDCiOS/source/material-components-ios/material_components_ios.bzl: in /private/var/tmp/_bazel_peterfriese/64605403d0c8c1779c313e5420fa5937/external/build_bazel_rules_apple/apple/ios.bzl: in /private/var/tmp/_bazel_peterfriese/64605403d0c8c1779c313e5420fa5937/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl: Extension file 'apple/internal/rule_factory.bzl' has errors
INFO: Elapsed time: 0,238s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: components/BottomAppBar
Undoing import rewrites for bazel...
```

Any idea what's wrong?

```
$bazel version
Build label: 0.22.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 13:00:18 2019 (1548680418)
Build timestamp: 1548680418
Build timestamp as int: 1548680418
```

Also, as I am not a committer, I cannot add the kokoro:force-run label to the PR.

**Comment by romoore** [comment]
@peterfriese I've invited you to our collaborators group. If you accept, kokoro will automatically run presubmits for your PRs.

**Comment by romoore** [comment]
@peterfriese My local bazel is 0.20.0-homebrew and I use Xcode 10.0 (there's [an outstanding issue where unit tests stall in Xcode 10.1](https://github.com/material-components/material-components-ios/issues/6259)). There *might* be interaction problems between bazel 0.22 and Xcode 10.1

**Comment by fluxminds** [comment]
@peterfriese Hi Peter, it seems the CI still errors out. You can probably cast the number to `(CGFloat)` to fix it.

**Comment by peterfriese** [comment]
Hi Wenyu, it seems like the PR now passes all checks (minus web site generation). @wenyuzhang666

**Comment by fluxminds** [comment]
@peterfriese Would you mind merging the `develop` branch into yours and run the CI? I think that would fix the website generation. Changes look good. But the website one is a required CI check, we need to make it pass before merging.

**Review by fluxminds — APPROVED** [review]

**Comment by peterfriese** [comment]
Looks like the failing website generation is independent from this PR (see #6546 for details). Suggest to merge this PR. @wenyuzhang666 WDYT?

**Comment by wenyuzhang666** [comment]
@peterfriese the website check has just been made not required to merge the PR by the team. Go head and merge it:) Thanks!

**Comment by fluxminds** [comment]
@peterfriese The website check has just been made not required by team. The PR was merged. Thanks!
